apiVersion: v1
kind: PersistentVolume
metadata:
  name: orthanc-local-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/k8s/orthanc-db # ruta fisica
---
#PVC Orthanc para enlazarse al PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-storage-pvc
  namespace: orthanc-santiago
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: orthanc-local-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/k8s/keycloak-db
---
#PVC a KEYCLOAK
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  namespace: orthanc-santiago
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: keycloak-local-pv
  resources:
    requests:
      storage: 5Gi
