apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-config
  namespace: orthanc-santiago
data:
  PUBLIC_DOMAIN: "http://tfm-sch.imaging.i3m.upv.es"
  STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
  DICOM_WEB_PLUGIN_ENABLED: "true"
  STL_PLUGIN_ENABLED: "true"
  VERBOSE_ENABLED: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: orthanc-santiago
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
  KC_DB_USERNAME: "keycloak"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-auth-config
  namespace: orthanc-santiago
data:
  ENABLE_KEYCLOAK: "true"
  KEYCLOAK_URI: "http://keycloak:8080/realms/orthanc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-auth-permissions
  namespace: orthanc-santiago
data:
  permissions.json: |
    {
      "roles": {
        "admin-role": {
          "authorized-labels": ["*"],
          "permissions": [
            "anonymize",
            "audit-logs",
            "delete",
            "download",
            "modify",
            "send",
            "share",
            "view",
            "worklists",
            "admin-permissions",
            "edit-labels",
            "q-r-remote-modalities",
            "settings",
            "upload"
          ]
        },
        "doctor-role": {
          "authorized-labels": ["*"],
          "permissions": [
            "view",
            "download",
            "share",
            "send"
          ]
        },
        "external-role": {
          "authorized-labels": [
            "external",
            "Label3",
            "Label5"
          ],
          "permissions": [
            "view",
            "download"
          ]
        }
      },
      "available-labels": []
    }
