apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-auth-service
  namespace: orthanc-santiago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc-auth-service
  template:
    metadata:
      labels:
        app: orthanc-auth-service
    spec:
      initContainers:
      - name: wait-for-keycloak
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z keycloak 8080; do echo waiting for keycloak; sleep 5; done']
      containers:
      - name: orthanc-auth-service
        image: orthancteam/orthanc-auth-service:26.2.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: orthanc-config
        - configMapRef:
            name: orthanc-auth-config
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: orthanc-secrets
              key: AUTH_SECRET_KEY
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: orthanc-secrets
              key: KC_CLIENT_SECRET
        - name: USERS
          valueFrom:
            secretKeyRef:
              name: orthanc-secrets
              key: SVC_USERS
        - name: PUBLIC_ORTHANC_ROOT
          value: "$(PUBLIC_DOMAIN)/orthanc/"
        - name: PUBLIC_LANDING_ROOT
          value: "$(PUBLIC_DOMAIN)/orthanc/ui/app/token-landing.html"
        - name: PUBLIC_OHIF_ROOT
          value: "$(PUBLIC_DOMAIN)/ohif/"
        volumeMounts:
        - name: permissions
          mountPath: /orthanc_auth_service/permissions.json
          subPath: permissions.json
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        initialDelaySeconds: 20
        periodSeconds: 20
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "300m"
          memory: "256Mi"
      volumes:
      - name: permissions
        configMap:
          name: orthanc-auth-permissions

---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-auth-service
  namespace: orthanc-santiago
spec:
  type: ClusterIP
  selector:
    app: orthanc-auth-service
  ports:
  - port: 8000
    targetPort: 8000
